### PR TITLE
Filter option

### PR DESCRIPTION
**Pull request by chrmarti**
I needed a way to filter down the installations and repositories the app is installed on. Posting here in case others find this useful.

### CODE REVIEW

**Comment by bkeepers** [comment]
Thanks @chrmarti. This seems reasonable, but could you give a little more insight into your use case? I'm mostly just curious.

**Comment by chrmarti** [comment]
I have a bot that is used on multiple accounts, so I had to make it publicly available. Some large accounts outside my control then installed the bot on all their repositories slowing the bot down because it would go through many repositories only to find that there was no config in their `.github/` folder. I'm using the filter to skip over these installations.

**Comment by chrmarti** [comment]
Still relevant, I'm using a patched version at the moment.

**Comment by chrmarti** [comment]
Still relevant, nothing changed.

**Comment by bkeepers** [comment]
Thanks @chrmarti for your patience. This is published as 1.2.0

**Comment by chrmarti** [comment]
Thanks @bkeepers !

**Pull request merged**
