### PR TITLE
fix #27: use name property instead of event

### LINKED ISSUE #27: Error: Propery `event` is deprecated, use `name`
Logs of my bot are full of it. It seems to be coming from here: https://github.com/probot/scheduler/blob/59bab48fd791826a463ef06d508fb47f6367d2d2/index.js#L57-L60

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by rafaelfranca** [comment]
:shipit:

**Comment by jleach** [comment]
@bkeepers Any chance we can get this one merged and published? It's a pretty small change.

**Comment by jleach** [comment]
@bkeepers This is a useful package. Any chance I can help get a few fixes in and an update published? If not maybe archive the project so people know its status.

**Comment by ahmadnassri** [comment]
will this be merged any time soon?

**Comment by intolerance** [comment]
@bkeepers Brandon, can you please review this PR? We are getting `deprecated` warnings due to it.

**Comment by dessant** [comment]
Same here, app logs are being flooded with warnings.

**Comment by intolerance** [comment]
@probot Can someone please take a look at these PR's?

**Comment by jleach** [comment]
I think they're radio silent. I went ahead and applied this patch and reposted the package to our corporate repo; You can install `@bcgov/probot-scheduler`.

**Comment by dessant** [comment]
The [commit](https://github.com/probot/scheduler/commit/0da3a0005c0619201bb26a9d20a3ac985930e6d4) can also be installed from GitHub until this is merged, add this to `package.json`:

```
  "dependencies": {
    "probot-scheduler": "probot/scheduler#0da3a0005c0619201bb26a9d20a3ac985930e6d4"
  },
```

**Comment by dessant** [comment]
@hiimbex, could this be merged and published? We are ready to offer our best squirrel in exchange.

**Review by hiimbex — APPROVED** [review]
Sorry y'all couldn't get this merged sooner. For context, Brandon and I both left GitHub.

I'll merge this, but the npm package belongs to Brandon: https://www.npmjs.com/package/probot-scheduler. I'll see if he or anyone else in the Probot slack has access/can grant.

**Comment by dessant** [comment]
@hiimbex, thanks for merging, and I wish you folks the best for your next adventure! :yum:

**Pull request merged**
